theme: 
title: Regi達o do Baixo S達o Francisco
name: Thiago Luiz
description: Regi達o do baixo S達o Francisco
logo: img/RioBSF.jpeg
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme # add this line to the plugins list if you already have one
